[package]
name = "primeutils"
version = "1.3.3"
authors = ["xyzatesz"]

[lib]
name = "primeutils_lib"
path = "src/lib.rs"

[[bin]]
name = "primeutils"
path = "src/main.rs"

[profile.release]
lto = true
panic = 'abort'

[dependencies]
rand = "0.3"